In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df= pd.read_csv(r'C:\Users\user\Downloads\my work software\pandas\krish naik\Fake-New-LSTM-master\train.csv')

In [3]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [4]:
df=df.dropna().reset_index()

In [5]:
X=df.drop('label', axis=1)

In [6]:
Y=df['label']

In [7]:
X.shape

(18285, 5)

In [8]:
Y.shape

(18285,)

In [9]:
import nltk
import re
from nltk.corpus import stopwords

In [10]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [11]:
from nltk.stem import WordNetLemmatizer
wl=WordNetLemmatizer()

In [12]:
messages= X['title'].copy()

In [13]:
main=[]
long=[]
for s in range(len(messages)):
    review= re.sub('[^a-zA-Z]',' ',messages[s])
    review= review.lower()
    review= review.split()
    main.append(review)
for word1 in main:
    l=[]
    for word in word1:
        if word not in stopwords.words('english'):
            l.append(ps.stem(word))
    long.append(l)
# now this is the longer method for removing the stopwords    

In [13]:
corpus=[]
ans=[]
for s in range(len(messages)):
    review= re.sub('[^a-zA-Z]',' ',messages[s])
    review= review.lower()
    review= review.split()
    
    corpus=[ps.stem(word)for word in review if word not in stopwords.words('english')]
    corpus = ' '.join(corpus)
    ans.append(corpus)
# this is the short method for removing the stopwords

In [14]:
ans

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [16]:
voc_size=10000

In [17]:
#one_hot_rep = [one_hot(word,voc_size) for word in ans]
onehot_repr=[one_hot(words,voc_size)for words in ans] 
onehot_repr

[[3712, 2907, 8068, 2825, 701, 530, 2280, 383, 2388, 283],
 [8479, 5073, 992, 9325, 9573, 7830, 978],
 [5193, 4939, 8210, 4445],
 [2698, 7858, 3558, 5991, 22, 6513],
 [9330, 9573, 4531, 9912, 3356, 7280, 9573, 3966, 9022, 6496],
 [9300,
  5950,
  9679,
  3838,
  1714,
  2622,
  5999,
  6090,
  6109,
  3687,
  1866,
  8785,
  705,
  2777,
  978],
 [8245, 1127, 6986, 9094, 4572, 1273, 4362, 5406, 8463, 9881, 7589],
 [1846, 7288, 2866, 3719, 8350, 761, 2622, 7654, 8463, 9881, 7589],
 [8178, 8249, 4757, 7878, 2452, 7462, 9935, 8123, 2622, 4552],
 [4621, 5273, 9158, 2792, 7874, 4, 9567, 7830],
 [2418, 3874, 5410, 2447, 4808, 9344, 6931, 4882, 692, 5529, 1435],
 [5991, 3713, 701, 7462, 2622, 8350],
 [4892, 3201, 2770, 8375, 6413, 3924, 9679, 5591, 3181],
 [2073, 1368, 235, 1854, 4672, 7406, 1505, 8463, 9881, 7589],
 [6248, 9117, 371, 7023, 3825, 8463, 9881, 7589],
 [2128, 4520, 4509, 799, 6454, 6227, 172, 1609, 7057, 6904],
 [8971, 588, 5073],
 [8490, 6490, 757, 5726, 2622, 8187, 2976, 978],

### Embedding process

In [18]:
# but for make every sentence of same length we have to find the highest length
max_length=0
for word in ans:
    word=word.split()
    if len(word)>max_length:
        max_length=len(word)
print(max_length)

# so from here we can see that the max length is 47

47


In [19]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=max_length)
embedded_docs

array([[   0,    0,    0, ...,  383, 2388,  283],
       [   0,    0,    0, ..., 9573, 7830,  978],
       [   0,    0,    0, ..., 4939, 8210, 4445],
       ...,
       [   0,    0,    0, ..., 8463, 9881, 7589],
       [   0,    0,    0, ..., 2337,  368, 3349],
       [   0,    0,    0, ..., 8032,  323, 5354]])

In [21]:
dimension=40
model=Sequential()
model.add(Embedding(voc_size,dimension,input_length=max_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 47, 40)            400000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
X_final=np.array(embedded_docs)
Y_final=np.array(Y)

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,Y_train,Y_test= train_test_split(X_final,Y_final,train_size=0.7,random_state=42)

#### Model Training

In [29]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 8s 40ms/step - loss: 0.3163 - accuracy: 0.8495 - val_loss: 0.1926 - val_accuracy: 0.9172
Epoch 2/10
200/200 [==============================] - 8s 38ms/step - loss: 0.1231 - accuracy: 0.9514 - val_loss: 0.1933 - val_accuracy: 0.9202
Epoch 3/10
200/200 [==============================] - 7s 37ms/step - loss: 0.0746 - accuracy: 0.9742 - val_loss: 0.2125 - val_accuracy: 0.9145
Epoch 4/10
200/200 [==============================] - 8s 38ms/step - loss: 0.0487 - accuracy: 0.9846 - val_loss: 0.2632 - val_accuracy: 0.9149
Epoch 5/10
200/200 [==============================] - 8s 38ms/step - loss: 0.0305 - accuracy: 0.9905 - val_loss: 0.3303 - val_accuracy: 0.9189
Epoch 6/10
200/200 [==============================] - 8s 38ms/step - loss: 0.0182 - accuracy: 0.9943 - val_loss: 0.3655 - val_accuracy: 0.9154
Epoch 7/10
200/200 [==============================] - 8s 39ms/step - loss: 0.0114 - accuracy: 0.9965 - val_loss: 0.3963 - val_accuracy: 0.9149

### Adding Dropout

### performance Matrix

In [30]:
Y_pred= model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [32]:
np.argmax(model.predict(X_test), axis=-1)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(Y_test,Y_pred)

array([[2847,  260],
       [ 235, 2144]], dtype=int64)

In [37]:
accuracy_score(Y_test,Y_pred)

0.9097703244622676